name: picturethat
description: "A daily prompt generator that provides interesting and unique photo prompts."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.12.1
  flutter_native_splash: ^2.4.4
  firebase_auth: ^5.5.1
  dotted_border: ^2.1.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  firebase_storage: ^12.4.4
  cloud_firestore: ^5.6.5
  flutter_riverpod: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

# make sure to run `dart run flutter_native_splash:create`
flutter_native_splash:
  color: "#FFF8F2"
  image: assets/splash_screen_light.png
  color_dark: "#17130B"
  image_dark: assets/splash_screen_dark.png

  android_12:
    icon_background_color: "#FFF8F2"
    image: assets/splash_screen_light.png
    icon_background_color_dark: "#17130B"
    image_dark: assets/splash_screen_dark.png
