name: picture_that
description: "A daily prompt generator that provides interesting and unique photo prompts."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.12.1
  flutter_native_splash: ^2.4.4
  firebase_auth: ^5.5.1
  dotted_border: ^2.1.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  firebase_storage: ^12.4.4
  cloud_firestore: ^5.6.5
  flutter_riverpod: ^2.6.1
  url_launcher: ^6.3.1
  photo_view: ^0.15.0
  shared_preferences: ^2.5.3
  package_info_plus: ^8.3.0
  skeletonizer: ^1.4.3
  flutter_launcher_icons: ^0.14.3
  share_plus: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/hero.png
    - assets/splash_screen_light.png
    - assets/splash_screen_dark.png

# make sure to run `dart run flutter_native_splash:create`
flutter_native_splash:
  color: "#FFF8F2"
  image: assets/splash_screen_light.png
  color_dark: "#17130B"
  image_dark: assets/splash_screen_dark.png

  android_12:
    icon_background_color: "#FFF8F2"
    image: assets/splash_screen_light.png
    icon_background_color_dark: "#17130B"
    image_dark: assets/splash_screen_dark.png

# make sure to run `dart run flutter_launcher_icons`
flutter_launcher_icons:
  image_path: "assets/icon_light.png"
  android: true
  adaptive_icon_background: "#FFF8F2"
  adaptive_icon_foreground: "assets/icon_light.png"
  adaptive_icon_monochrome: "assets/icon_dark.png"
  ios: true
  remove_alpha_ios: true
  background_color_ios: "#FFF8F2"
  image_path_ios_dark_transparent: "assets/icon_dark.png"
