// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7SjWYXaqiUAHB635fFE3zEaSwtZeC_Jo',
    appId: '1:983735759449:android:88cd7935d421f4532b7748',
    messagingSenderId: '983735759449',
    projectId: 'picturethat-65135',
    storageBucket: 'picturethat-65135.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCh4mT0WppQDTasb9cC8R86D2RTFkp5wfU',
    appId: '1:983735759449:web:0c9adc34c0c6212d2b7748',
    messagingSenderId: '983735759449',
    projectId: 'picturethat-65135',
    authDomain: 'picturethat-65135.firebaseapp.com',
    storageBucket: 'picturethat-65135.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMoEyfaweWi3jUX4qal8FgjoCJ2ZuS3pM',
    appId: '1:983735759449:ios:8eec37fc97339d932b7748',
    messagingSenderId: '983735759449',
    projectId: 'picturethat-65135',
    storageBucket: 'picturethat-65135.firebasestorage.app',
    iosBundleId: 'com.example.picturethat',
  );
}
